import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { acceptProviderBooking, completeProviderBooking, deleteProviderBookingCompletion, getBookingById, rejectProviderBooking, startProviderBooking, updateProviderBookingCompletion } from "../../../../../lib/booking";
import ZoomableImage from "../../../../components/common/ZoomableImage";

const pad = (value) => String(value).padStart(2, "0");
const dateKey = (date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
const startOfToday = () => { const value = new Date(); value.setHours(0, 0, 0, 0); return value; };

function toTwelveHour(value) {
  const [rawHour = 0, minute = 0] = String(value || "").split(":").map(Number);
  return { hour: String(rawHour % 12 || 12), minute: pad(minute), period: rawHour >= 12 ? "PM" : "AM" };
}

function toTwentyFourHour(hour, minute, period) {
  const parsedHour = Number(hour); const parsedMinute = Number(minute);
  if (!Number.isInteger(parsedHour) || parsedHour < 1 || parsedHour > 12 || !Number.isInteger(parsedMinute) || parsedMinute < 0 || parsedMinute > 59) return null;
  const converted = parsedHour % 12 + (period === "PM" ? 12 : 0);
  return `${pad(converted)}:${pad(parsedMinute)}`;
}

export default function ProviderBookingDetails() {
  const router = useRouter(); const { id } = useLocalSearchParams(); const bookingId = Array.isArray(id) ? id[0] : id;
  const [booking, setBooking] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [date, setDate] = useState(""); const [month, setMonth] = useState(() => new Date()); const [hour, setHour] = useState(""); const [minute, setMinute] = useState(""); const [period, setPeriod] = useState("AM"); const [note, setNote] = useState("");
  const [completionImages, setCompletionImages] = useState([]); const [editingCompletion, setEditingCompletion] = useState(false);
  const scheduleError = useMemo(() => {
    if (!hour && !minute) return "";
    const time = toTwentyFourHour(hour, minute, period);
    if (!time) return "Enter an hour from 1–12 and minutes from 00–59.";
    if (date && new Date(`${date}T${time}:00`).getTime() <= Date.now()) return "Select a time later than the current time.";
    return "";
  }, [date, hour, minute, period]);
  const load = useCallback(async () => { try { const result = await getBookingById(bookingId); const item = result.booking; setBooking(item); setDate(item.scheduledDate || ""); if (item.scheduledDate) { const [y, m] = item.scheduledDate.split("-").map(Number); setMonth(new Date(y, m - 1, 1)); } const clock = toTwelveHour(item.scheduledTime); setHour(item.scheduledTime ? clock.hour : ""); setMinute(item.scheduledTime ? clock.minute : ""); setPeriod(clock.period); setNote(item.providerNote || ""); } catch (e) { Alert.alert("Error", e?.response?.data?.message || "Unable to load booking."); } finally { setLoading(false); } }, [bookingId]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const run = async (action, success) => { try { setSaving(true); await action(); router.push({ pathname: "/ServiceProvider/(tabs)/booking/status-success", params: { title: success, bookingId } }); } catch (e) { Alert.alert("Unable to update booking", e?.response?.data?.message || "Please try again."); } finally { setSaving(false); } };
  const pickCompletionImages = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert("Permission required", "Allow photo access to attach completion images."); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsMultipleSelection: true, selectionLimit: 3, quality: 0.8 }); if (!result.canceled) setCompletionImages(result.assets.slice(0, 3)); };
  const updateCompletion = async () => { if (!note.trim()) return Alert.alert("Completion note required", "Describe the completed work."); try { setSaving(true); await updateProviderBookingCompletion(bookingId, note.trim(), completionImages); setCompletionImages([]); setEditingCompletion(false); await load(); Alert.alert("Updated", "Booking completion updated successfully."); } catch (e) { Alert.alert("Unable to update", e?.response?.data?.message || "Please try again."); } finally { setSaving(false); } };
  const deleteCompletion = () => Alert.alert("Delete completion?", "The completion note and photos will be removed and this booking will return to Working status.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { setSaving(true); await deleteProviderBookingCompletion(bookingId); setCompletionImages([]); setEditingCompletion(false); await load(); Alert.alert("Booking reopened", "The booking is now back in Working status."); } catch (e) { Alert.alert("Unable to delete", e?.response?.data?.message || "Please try again."); } finally { setSaving(false); } } }]);
  const accept = () => { const time = toTwentyFourHour(hour, minute, period); if (!date) return Alert.alert("Select a date", "Choose a service date from the calendar."); if (!time) return Alert.alert("Invalid time", "Enter an hour from 1–12 and minutes from 00–59."); const selected = new Date(`${date}T${time}:00`); if (selected.getTime() <= Date.now()) return Alert.alert("Past time not allowed", "Select a future date and time."); run(() => acceptProviderBooking(bookingId, date, time), "Booking Accepted"); };
  if (loading || !booking) return <View className="flex-1 items-center justify-center bg-[#EAF2EF]"><ActivityIndicator color="#008568" /></View>;
  const customer = booking.customer?.customerProfile; const customerName = customer ? `${customer.firstName} ${customer.lastName}` : "Customer";
  return <ScrollView className="flex-1 bg-[#EAF2EF]" contentContainerStyle={{ padding: 20, paddingTop: 52, paddingBottom: 40 }} keyboardShouldPersistTaps="handled">
    <View className="flex-row items-center"><Pressable onPress={() => router.back()} className="h-10 w-10 items-center justify-center rounded-full bg-white"><Ionicons name="arrow-back" size={21} color="#17342F" /></Pressable><View className="ml-3 flex-1"><Text className="text-xl font-bold text-[#17342F]">Booking Details</Text><Text className="text-[10px] text-[#82908D]">Booking ID: {booking.id.slice(0, 8)}</Text></View><Text className="text-[10px] font-bold text-[#008568]">{booking.status}</Text></View>
    <Title text="Customer" /><Card><Text className="font-bold text-[#17342F]">{customerName}</Text><Text className="mt-1 text-xs text-[#82908D]">{booking.phoneNumber}</Text><Pressable onPress={() => router.push({ pathname: "/ServiceProvider/(tabs)/booking/messages/[bookingId]", params: { bookingId: booking.id, name: customerName } })} className="mt-3 items-center rounded-full bg-[#008568] py-3"><Text className="text-xs font-bold text-white">MESSAGE CUSTOMER</Text></Pressable></Card>
    <Title text="Service Details" /><Card><Row label="Problem" value={booking.problem} /><Row label="Location" value={booking.serviceLocation} /><Row label="Customer note" value={booking.note || "None"} />{booking.scheduledDate && <><Row label="Service date" value={booking.scheduledDate} /><Row label="Service time" value={String(booking.scheduledTime).slice(0, 5)} /></>}</Card>
    {!!booking.images?.length && <><Title text="Attached Photos" /><ScrollView horizontal>{booking.images.map((image) => <ZoomableImage key={image.id} uri={image.imageUrl} containerClassName="mr-3" imageClassName="h-24 w-28 rounded-2xl" />)}</ScrollView></>}
    {booking.status === "PENDING" && <><Title text="Accept and Schedule" /><Calendar value={date} month={month} onMonthChange={setMonth} onChange={setDate} /><Card><Text className="mb-3 font-bold text-[#17342F]">Add the time</Text><View className="flex-row items-center"><TimeBox value={hour} onChangeText={(v) => setHour(v.replace(/\D/g, "").slice(0, 2))} placeholder="09" /><Text className="mx-2 text-xl font-bold">:</Text><TimeBox value={minute} onChangeText={(v) => setMinute(v.replace(/\D/g, "").slice(0, 2))} placeholder="25" /><View className="ml-3 flex-row rounded-xl bg-[#E7F2EE] p-1">{["AM", "PM"].map((item) => <Pressable key={item} onPress={() => setPeriod(item)} className={`rounded-lg px-3 py-3 ${period === item ? "bg-[#008568]" : ""}`}><Text className={`text-xs font-bold ${period === item ? "text-white" : "text-[#008568]"}`}>{item}</Text></Pressable>)}</View></View><Text className="mt-2 text-[10px] text-[#82908D]">Selected: {date || "Choose a date"} · {hour || "--"}:{minute || "--"} {period}</Text>{!!scheduleError && <Text className="mt-2 text-[11px] font-semibold text-red-600">{scheduleError}</Text>}<Pressable disabled={saving || !!scheduleError} onPress={accept} className={`mt-4 items-center rounded-full py-3 ${scheduleError ? "bg-[#75B5A6]" : "bg-[#008568]"}`}><Text className="font-bold text-white">ACCEPT BOOKING</Text></Pressable><Pressable disabled={saving} onPress={() => run(() => rejectProviderBooking(bookingId, note), "Booking Rejected")} className="mt-3 items-center rounded-full border border-red-500 py-3"><Text className="font-bold text-red-600">REJECT</Text></Pressable></Card></>}
    {booking.status === "ACCEPTED" && <Pressable disabled={saving} onPress={() => run(() => startProviderBooking(bookingId), "Work Started")} className="mt-6 items-center rounded-full bg-[#008568] py-4"><Text className="font-bold text-white">START WORKING</Text></Pressable>}
    {booking.status === "WORKING" && <><Title text="Completion details" /><TextInput value={note} onChangeText={setNote} multiline placeholder="Describe the completed work..." className="min-h-[110px] rounded-2xl bg-white p-4" /><CompletionImagePicker images={completionImages} onPick={pickCompletionImages} onRemove={(index) => setCompletionImages((items) => items.filter((_, itemIndex) => itemIndex !== index))} /><Pressable disabled={saving || !note.trim()} onPress={() => run(() => completeProviderBooking(bookingId, note.trim(), completionImages), "Booking Completed")} className={`mt-4 items-center rounded-full py-4 ${note.trim() ? "bg-[#008568]" : "bg-[#75B5A6]"}`}><Text className="font-bold text-white">MARK BOOKING AS COMPLETED</Text></Pressable></>}
    {booking.status === "COMPLETED" && <><Text className="mt-8 text-center text-2xl font-bold text-[#008568]">COMPLETED</Text><Card><Text className="text-xs font-bold text-[#82908D]">COMPLETION NOTE</Text>{editingCompletion ? <><TextInput value={note} onChangeText={setNote} multiline className="mt-3 min-h-[110px] rounded-2xl bg-[#F1F6F4] p-4 text-[#17342F]" /><CompletionImagePicker images={completionImages} onPick={pickCompletionImages} onRemove={(index) => setCompletionImages((items) => items.filter((_, itemIndex) => itemIndex !== index))} /><View className="mt-4 flex-row gap-3"><Pressable onPress={() => { setEditingCompletion(false); setCompletionImages([]); setNote(booking.providerNote || ""); }} className="flex-1 items-center rounded-full border border-[#B9CAC5] py-3"><Text className="font-bold text-[#65736F]">CANCEL</Text></Pressable><Pressable disabled={saving || !note.trim()} onPress={updateCompletion} className="flex-1 items-center rounded-full bg-[#008568] py-3"><Text className="font-bold text-white">SAVE</Text></Pressable></View></> : <><Text className="mt-2 text-sm leading-6 text-[#17342F]">{booking.providerNote || "No completion note"}</Text><View className="mt-4 flex-row gap-3"><Pressable onPress={() => setEditingCompletion(true)} className="flex-1 items-center rounded-full bg-[#008568] py-3"><Text className="font-bold text-white">EDIT</Text></Pressable><Pressable disabled={saving} onPress={deleteCompletion} className="flex-1 items-center rounded-full border border-red-500 py-3"><Text className="font-bold text-red-600">DELETE</Text></Pressable></View></>}</Card></>}
  </ScrollView>;
}

function Calendar({ value, month, onMonthChange, onChange }) {
  const days = useMemo(() => { const year = month.getFullYear(); const monthIndex = month.getMonth(); const firstDay = new Date(year, monthIndex, 1).getDay(); const count = new Date(year, monthIndex + 1, 0).getDate(); return [...Array(firstDay).fill(null), ...Array.from({ length: count }, (_, index) => new Date(year, monthIndex, index + 1))]; }, [month]);
  const today = startOfToday(); const previousMonth = () => { const target = new Date(month.getFullYear(), month.getMonth() - 1, 1); if (target.getFullYear() < today.getFullYear() || (target.getFullYear() === today.getFullYear() && target.getMonth() < today.getMonth())) return; onMonthChange(target); };
  return <View className="mb-4 rounded-3xl bg-white p-4"><View className="mb-4 flex-row items-center justify-between"><Pressable onPress={previousMonth} className="p-2"><Ionicons name="chevron-back" size={18} color="#17342F" /></Pressable><Text className="font-bold text-[#17342F]">{month.toLocaleDateString([], { month: "long", year: "numeric" })}</Text><Pressable onPress={() => onMonthChange(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="p-2"><Ionicons name="chevron-forward" size={18} color="#17342F" /></Pressable></View><View className="flex-row">{["S", "M", "T", "W", "T", "F", "S"].map((day, index) => <Text key={`${day}-${index}`} className="w-[14.28%] text-center text-[10px] text-[#82908D]">{day}</Text>)}</View><View className="mt-2 flex-row flex-wrap">{days.map((day, index) => { if (!day) return <View key={`empty-${index}`} className="h-10 w-[14.28%]" />; const key = dateKey(day); const disabled = day < today; const selected = key === value; return <Pressable key={key} disabled={disabled} onPress={() => onChange(key)} className="h-10 w-[14.28%] items-center justify-center"><View className={`h-8 w-8 items-center justify-center rounded-full ${selected ? "bg-[#008568]" : ""}`}><Text className={`text-xs font-semibold ${disabled ? "text-[#CBD3D0]" : selected ? "text-white" : "text-[#17342F]"}`}>{day.getDate()}</Text></View></Pressable>; })}</View></View>;
}

const TimeBox = (props) => <TextInput {...props} keyboardType="number-pad" maxLength={2} className="h-12 w-16 rounded-xl bg-[#E7F2EE] text-center text-lg font-bold text-[#17342F]" />;
const CompletionImagePicker = ({ images, onPick, onRemove }) => <View className="mt-4"><Text className="mb-2 text-xs font-bold text-[#17342F]">Completion photos (up to 3)</Text><View className="flex-row flex-wrap gap-3">{images.map((image, index) => <View key={`${image.uri}-${index}`} className="relative"><Image source={{ uri: image.uri }} className="h-24 w-24 rounded-2xl" /><Pressable onPress={() => onRemove(index)} className="absolute -right-2 -top-2 h-7 w-7 items-center justify-center rounded-full bg-red-500"><Ionicons name="close" size={17} color="white" /></Pressable></View>)}</View><Pressable onPress={onPick} className="mt-3 flex-row items-center justify-center rounded-2xl border border-dashed border-[#8FB1A8] bg-white py-4"><Ionicons name="images-outline" size={21} color="#008568" /><Text className="ml-2 text-xs font-bold text-[#008568]">{images.length ? "CHANGE PHOTOS" : "ADD COMPLETION PHOTOS"}</Text></Pressable></View>;
const Card = ({ children }) => <View className="mb-4 rounded-3xl bg-white p-4">{children}</View>;
const Title = ({ text }) => <Text className="mb-2 mt-6 font-bold text-[#17342F]">{text}</Text>;
const Row = ({ label, value }) => <View className="mb-3 flex-row"><Text className="w-28 text-[10px] font-bold text-[#17342F]">{label}</Text><Text className="flex-1 text-[11px] text-[#74827F]">{value}</Text></View>;
